### ISSUE TITLE
Optional Allow Alter Table Flag on conflict

### ISSUE THREAD

**Issue by bh2smith** [bh2smith/dune-sync#102]
Given the two indexed insertion methods (upsert #93 and ignore #101) our validation can determine if uniqueness constraint exists on the table for the given "index columns". The program knows enough to propose the precise alter table command the user must execute in order for the insertion to work. Since the provided DB_URL has write access to the database, we could perform the execution for them. This might be more convenient than logging an error and failing. 

I propose that we add a runtime flag `allow_alter_table: bool` (or some better name) _**with a default of True**_.

In the case the uniqueness constraint fails, we log a warning and proceed with table altering execution.

What does everyone think? cc @fleupold and @mooster531.

**Comment by mooster531** [comment]
Sounds like too much magic to me, personally I feel :-1: on it, especially with the default behaviour being "allow". I'm accepting whatever @fleupold votes though.

**Comment by bh2smith** [comment]
> especially with the default behaviour being "allow"

We could also make the default false so the user explicitly gives permission to perform these operations.

**Comment by fleupold** [comment]
Agree that this case sounds edgy enough that it should probably be handled by whoever created the uniqueness constraints in the first place (and which are no longer met). Logging the concrete statement to make it easy to debug this error makes sense imo though.

**Comment by bh2smith** [comment]
Okie, so then I will leave it as is, the error log already includes the precise `ALTER TABLE` statement required to successfully perform the insertion for the uniqueness constraint.
