### ISSUE TITLE
Add a schema option for the postgres source and destination

### ISSUE THREAD

**Issue by ferrau10** [bh2smith/dune-sync#107]
I want to specify in which schema the table should be created inside of my postgres database. 
I tried specifying in the configuration a table name with the following structure: schema_name.table_name

jobs:
  - name: d2p-solver-payments
    source:
      ref: Dune
      query_id: 4335147
      query_engine: medium
      poll_frequency: 5
    destination:
      ref: PG
      table_name: aurelie.src_dune_solver_payments

But the table was created in the public schema instead of the aurelie schema (see screenshot)
<img width="588" alt="Screenshot 2024-12-03 at 15 41 33" src="https://github.com/user-attachments/assets/b9feb670-ae4f-4af5-b38e-01b82ce83685">

maybe we could add a new option for postgres on top of table_name which is schema_name (default to public) OR treat dots inside the table name as a schema.table

**Comment by bh2smith** [comment]
Hey thanks for this! I had been under the impression that this would be specified by the `database` attribute of the `DB_URL`... If this is not the case, we can look into it. makes perfect sense to have.
