### ISSUE TITLE
Installing poetry does not work 

### ISSUE THREAD

**Issue by ferrau10** [bh2smith/dune-sync#108]
![Screenshot 2024-12-03 at 15 22 45](https://github.com/user-attachments/assets/22c48eb2-799b-403f-a397-b6092141a6a6)

workaround was to use dev container

**Comment by bh2smith** [comment]
cc @mooster531

**Comment by bh2smith** [comment]
Could it be that you didn't have python 3.13 installed? I tried this out too and got past that step... This poetry thing doesn't work for me either.

**Comment by bh2smith** [comment]
So it turns out the make file is a bit overkill for installation (given the simplicity of poetry in the first place). 

I propose the new instructions be:

```sh
poetry install
poetry shell
make fmt
make check
make test
...etc
```
