### ISSUE TITLE
Log job execution and completion

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#117]
In order to have some basic observability as to what is going on under the hood, it would help if each job could create a log line when it is started and when it is complete. In the completion log line some metadata (e.g. time it ran and how many records it processed) would additionally be helpful.

Currently it's not possible to see anything from the logs.

**Comment by bh2smith** [comment]
This is definitely already happening. Have you checked std out? There may not be an official start log but the dune logs executing with a time stamp. I'll run a sample later to show what's already available. Let us know what you think is missing.

**Comment by bh2smith** [comment]
Ok. I see it's not the job that's logging but the save on destination. I will move some logs into the job itself like start and end.
