### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by mooster531** [bh2smith/dune-sync#87]
See title. Project needs a LICENSE file.

**Comment by bh2smith** [comment]
Looks like the [last project](https://github.com/cowdao-grants/mb-billing/blob/main/LICENSE) done by @cowanator used an MIT Licence. However, other projects in the @cowdao-grants or have GNU...

GNU - https://github.com/cowdao-grants/cow-shed/blob/main/LICENSE

LGPL - https://github.com/cowdao-grants/milkman

I guess we can just go with whatever @fleupold prefers here.

**Comment by c3rnst** [comment]
HI there - may I suggest you take a look into the signed T&Cs: https://ipfs.io/ipfs/Qmag8BoNWhBnJ7TFyv2hzWwtoH17Xo7m9468NY6bN8sR6U - Section 8: 
![Screenshot 2024-11-25 at 09 02 30](https://github.com/user-attachments/assets/8f9094bb-ea99-4947-b4a5-17e9d8a01996)
