### ISSUE TITLE
Allow running a single job (or a subset of jobs) via command line

### ISSUE THREAD

**Issue by fleupold** [bh2smith/dune-sync#99]
It's beneficial to define all available jobs in a single config file to share datasources and other parts of the logic. However, when scheduling sync jobs we might want to have different cadences for different jobs and not always be forced to run all the jobs at the same time.

It would therefore be nice to allow adding a command line argument that can specify a single (or multiple) job names which will get executed from the config file.

**Comment by bh2smith** [comment]
Should be pretty straightforward with a runtime argument `jobs : list[str] | None` (default None) where None represents "all".
